[package]
name = "tfi"
version = "0.3.1"
authors = ["Confio GmbH"]
edition = "2018"
description = "Common tfi types"
license = "Apache-2.0"
repository = "https://github.com/confio/tfi"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.13.1"
cosmwasm-storage = "1.0.0-beta6"
cosmwasm-std = "1.0.0-beta6"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0-beta6"
tfi-mocks = { path = "../mocks", version = "0.3.1" }
