[package]
name = "tfi"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Common tfi types"
license = "Apache-2.0"
repository = "https://github.com/confio/tfi"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8.0-rc1" }
cosmwasm-storage = { version = "0.16.0-rc5" }
cosmwasm-std = { version = "0.16.0-rc5" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.16.0-rc5"
tfi-mocks = { path = "../mocks", version = "0.1.0" }

