[package]
name = "tfi-mocks"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Mocks for tfi tests"
license = "Apache-2.0"
repository = "https://github.com/confio/tfi"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfi = { path = "../tfi", version = "0.1.0" }
cw20 = "=0.10"
cosmwasm-storage = "=1.0.0-beta"
cosmwasm-std = "=1.0.0-beta"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
