[package]
name = "tfi-mocks"
version = "0.0.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Mocks for tfi tests"
license = "Apache-2.0"
repository = "https://github.com/confio/tfi"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfi = { path = "../tfi", version = "0.0.2" }
cw20 = { version = "0.6" }
cosmwasm-storage = { version = "0.14.0" }
cosmwasm-std = { version = "0.14.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
